train_root: datasets/train
train_img_dir: images
raw_df: train.csv
concat_df: new_train.csv
age_train_df: new_train_age_label.csv
age_valid_df: new_valid_age_label.csv
gender_train_df: new_train_gender_label.csv
gender_valid_df: new_valid_gender_label.csv
mask_train_df: new_train_mask_label.csv
mask_valid_df: new_valid_mask_label.csv
eval_df: datasets/eval/info.csv
save_df: datasets/eval/submission.csv

seed: 2021
num_workers: 4
pin_memory: True
lr_rate: 0.001
batch_size: 64
epochs: 10
k_fold: 1
age_class: 3
mask_class: 3
gender_class: 2
multi_class: 8
num_classes: 18
model: resnet50
loss: label_smoothing
optimizer: Adam
