train_root: datasets/train
train_img_dir: images
raw_df: train.csv
concat_df: new_train.csv
valid_df: new_valid.csv
age_train_df: new_train_age_label.csv
age_valid_df: new_valid_age_label.csv
gender_train_df: new_train_gender_label.csv
gender_valid_df: new_valid_gender_label.csv
mask_train_df: new_train_mask_label.csv
mask_valid_df: new_valid_mask_label.csv
eval_df: datasets/eval/info.csv
save_df: datasets/eval/submission1.csv

seed: 2023
num_workers: 8
pin_memory: True
lr_rate: 0.001
batch_size: 128
epochs: 100
multi_class: 8
g_class: 2
m_class: 3
a_class: 3
k_fold: 1
model: ViT
g_loss: f1
m_loss: f1
a_loss: f1
optimizer: Lion
